// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for Android and iOS.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnJR8Qi5P0Df4MNwY1DYAuT6BWdomI-38',
    appId: '1:242506685422:android:d61002ae6101c8c6cf4cff',
    messagingSenderId: '242506685422',
    projectId: 'evently-mon-c14-5ea4d',
    storageBucket: 'evently-mon-c14-5ea4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9dhPSix209bLnc3p9-nj-ZL1ZqHMp9lE',
    appId: '1:242506685422:ios:c1e7b1064032baf8cf4cff',
    messagingSenderId: '242506685422',
    projectId: 'evently-mon-c14-5ea4d',
    storageBucket: 'evently-mon-c14-5ea4d.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );
}
